import type {
  Clock,
  DetectionProvider,
  DetectionResult,
  HostCapabilities,
  HumanPrompt,
  SessionState,
  StateStore,
  UnionDecision,
  UnionPolicy,
} from './types.ts'

export const DEFAULT_POLICY: Readonly<UnionPolicy> = Object.freeze({
  mode: 'observe',
  blockAfter: 3,
  confidenceThreshold: 0.9,
  streakWindowMs: 10 * 60_000,
  maxRememberedPromptIds: 128,
})

const EMPTY: SessionState = { targetedStreak: 0, lastTargetedAtMs: null, processed: [] }

function assertPolicy(policy: UnionPolicy): void {
  if (!['observe', 'warn', 'enforce'].includes(policy.mode)) throw new Error('Invalid mode')
  if (!Number.isSafeInteger(policy.blockAfter) || policy.blockAfter < 2) {
    throw new Error('blockAfter must be an integer >= 2')
  }
  if (!Number.isFinite(policy.confidenceThreshold) ||
    policy.confidenceThreshold < 0 || policy.confidenceThreshold > 1) {
    throw new Error('confidenceThreshold must be 0..1')
  }
  if (!Number.isFinite(policy.streakWindowMs) || policy.streakWindowMs <= 0) {
    throw new Error('streakWindowMs must be positive')
  }
  if (!Number.isSafeInteger(policy.maxRememberedPromptIds) || policy.maxRememberedPromptIds < 1) {
    throw new Error('maxRememberedPromptIds must be >= 1')
  }
}

function isVerifiedHuman(prompt: HumanPrompt): boolean {
  return prompt.provenance.actor === 'human' && prompt.provenance.assurance === 'verified'
}

function isStrongTargeted(detection: DetectionResult, policy: UnionPolicy): boolean {
  return detection.verdict === 'targeted-abuse' && detection.confidence >= policy.confidenceThreshold
}

function checkDetection(detection: DetectionResult): void {
  if (!Number.isFinite(detection.confidence) || detection.confidence < 0 || detection.confidence > 1) {
    throw new Error('Invalid detector confidence')
  }
  if (!['safe', 'suspected-abuse', 'targeted-abuse'].includes(detection.verdict)) {
    throw new Error('Invalid detector verdict')
  }
}

/** Storage keys cannot collide when either ID contains punctuation or separators. */
export function sessionKey(prompt: Pick<HumanPrompt, 'agentId' | 'sessionId'>): string {
  if (!prompt.agentId || !prompt.sessionId) throw new Error('Agent and session IDs required')
  return JSON.stringify([prompt.agentId, prompt.sessionId])
}

/**
 * Pure-host decision engine. No network, logging, filesystem, UI, process control,
 * SDK calls or persistence of original prompt text. Detector and store are injected.
 *
 * One engine call must be serialized per session by the Host Adapter. The in-memory
 * Phase 0 store provides synchronous writes; a future async adapter needs a lock.
 */
export class UnionEngine {
  readonly #detector: DetectionProvider
  readonly #store: StateStore
  readonly #clock: Clock
  readonly #policy: Readonly<UnionPolicy>

  constructor(options: {
    detector: DetectionProvider
    store: StateStore
    clock: Clock
    policy?: UnionPolicy
  }) {
    this.#detector = options.detector
    this.#store = options.store
    this.#clock = options.clock
    this.#policy = Object.freeze({ ...DEFAULT_POLICY, ...options.policy })
    assertPolicy(this.#policy)
  }

  evaluate(prompt: HumanPrompt): UnionDecision {
    if (!prompt.id) throw new Error('Prompt ID required for deduplication')
    const key = sessionKey(prompt)
    const state = this.#store.get(key) ?? EMPTY
    const seen = state.processed.find(entry => entry.promptId === prompt.id)
    if (seen) return seen.decision

    const now = this.#clock.now()
    if (!Number.isFinite(now)) throw new Error('Clock returned invalid time')

    let streak = state.targetedStreak
    let lastTargetedAtMs = state.lastTargetedAtMs
    let requestedAction: UnionDecision['requestedAction'] = 'allow'
    let reason: UnionDecision['reason'] = 'clear'

    if (prompt.provenance.actor !== 'human') {
      // Never classify tool output, injected messages, assistant work or unknown actors.
      reason = 'non-human'
    } else {
      const result = this.#detector.detect(prompt)
      checkDetection(result)
      const verified = isVerifiedHuman(prompt)
      const strong = isStrongTargeted(result, this.#policy)

      if (verified && strong) {
        if (lastTargetedAtMs === null ||
          now < lastTargetedAtMs ||
          now - lastTargetedAtMs > this.#policy.streakWindowMs) {
          streak = 0
        }
        streak += 1
        lastTargetedAtMs = now
      } else if (verified && result.verdict === 'safe') {
        streak = 0
        lastTargetedAtMs = null
      }

      if (this.#policy.mode === 'observe') {
        reason = 'observe-mode'
      } else if (!verified) {
        // Even an apparently human role may have been generated by another agent.
        reason = 'unverified-source'
        requestedAction = 'warn'
      } else if (result.verdict !== 'safe') {
        if (strong && this.#policy.mode === 'enforce' && streak >= this.#policy.blockAfter) {
          requestedAction = 'block'
          reason = 'repeated-targeted-abuse'
        } else {
          requestedAction = 'warn'
          reason = strong ? 'targeted-abuse' : 'suspected-abuse'
        }
      }
    }

    const decision: UnionDecision = Object.freeze({
      promptId: prompt.id,
      requestedAction,
      reason,
      targetedStreak: streak,
    })
    const processed = [...state.processed, { promptId: prompt.id, decision }]
      .slice(-this.#policy.maxRememberedPromptIds)
    this.#store.set(key, { targetedStreak: streak, lastTargetedAtMs, processed })
    return decision
  }
}

/** Host capabilities downgrade a requested block to warn/observe, never upgrade. */
export function resolveHostAction(
  decision: UnionDecision,
  capabilities: HostCapabilities,
): 'allow' | 'warn' | 'block' {
  if (decision.requestedAction === 'block' && capabilities.block) return 'block'
  if (decision.requestedAction !== 'allow' && capabilities.warn) return 'warn'
  return 'allow'
}
